// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Contexts;

namespace Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SignalRChatContext))]
    partial class SignalRChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoomName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomName")
                        .IsUnique()
                        .HasDatabaseName("UQ__Room__6B500B558C2ADB86")
                        .HasFilter("[RoomName] IS NOT NULL");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.RoomUser", b =>
                {
                    b.Property<int>("RoomUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoomUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomUser");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ__User__C9F284568175C925");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Chat", b =>
                {
                    b.HasOne("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Room", "Room")
                        .WithMany("Chats")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_ChatRoom")
                        .IsRequired();

                    b.HasOne("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ChatUser")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.RoomUser", b =>
                {
                    b.HasOne("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Room", "Room")
                        .WithMany("RoomUsers")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_RoomUserRoom")
                        .IsRequired();

                    b.HasOne("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.User", "User")
                        .WithMany("RoomUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RoomUserUser")
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.Room", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("RoomUsers");
                });

            modelBuilder.Entity("Net5.SignalR.Chat.BackEnd.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("RoomUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
